name: Adobe Price Checker

on:
  schedule:
    - cron: "0 6,12,18,23 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run price checker
        run: |
          python price_checker.py
# reload

